plugins:
  - semantic-release-gitmoji
  - - "@semantic-release/npm"
    - npmPublish: false
      pkgRoot: /Packages/jp.virtualaviation.virtual-cns
  - "@semantic-release/github"
  - "@semantic-release/git"
